### ISSUE TITLE
Android app crashes on second try to attach an image

### ISSUE THREAD

**Issue by paradonym** [devRant/devRant#297]
1. Open a new Rant
2. attach an image
3. remove the attached image
4. attach another (or the same) image again

the gallery app opens and shows an devrant app-crash on top.

stats:
- I don't know how to see the version of the devrant app, but Google Play currently doesn't has an update.
- WiFi (5 GHz, full signal) has been active
- some other apps were running, but not actively - RAM should have been enough
- OnePlus 3T (6GB RAM - Snapdragon 821 Quadcore)
- Android 8.0.0 
- Android Security Patch: 1. December 2017

if you need more (ADB log or so) contact me...

**Comment by paradonym** [comment]
ADB LogCat of a "second image attachment"crash seemingly from yesterday.

https://zerobin.net/?3288abef9192c0f7#31l2Xei+LAIDVzvoiZLsuu71gXVzHxBBg59VxYWddt8=

This document will expire in one month, so please make a local copy if you need it.

**Comment by olback** [comment]
Same issue here.

@paradonym Saving the log as a comment instead.
```
01-09 11:43:39.782 32463 32463 D AndroidRuntime: Shutting down VM
01-08 15:25:52.544  6822  6822 E AndroidRuntime: FATAL EXCEPTION: main
01-08 15:25:52.544  6822  6822 E AndroidRuntime: Process: com.hexicallabs.devrant, PID: 6822
01-08 15:25:52.544  6822  6822 E AndroidRuntime: java.lang.IllegalStateException: org.appcelerator.titanium.util.TiBlobLruCache.sizeOf() is reporting inconsistent results!
01-08 15:25:52.544  6822  6822 E AndroidRuntime: 	at android.support.v4.util.LruCache.trimToSize(LruCache.java:167)
01-08 15:25:52.544  6822  6822 E AndroidRuntime: 	at android.support.v4.util.LruCache.evictAll(LruCache.java:271)
01-08 15:25:52.544  6822  6822 E AndroidRuntime: 	at org.appcelerator.titanium.TiApplication.onTrimMemory(TiApplication.java:415)
01-08 15:25:52.544  6822  6822 E AndroidRuntime: 	at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:5585)
01-08 15:25:52.544  6822  6822 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1895)
01-08 15:25:52.544  6822  6822 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
01-08 15:25:52.544  6822  6822 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-08 15:25:52.544  6822  6822 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6809)
01-08 15:25:52.544  6822  6822 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 15:25:52.544  6822  6822 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
01-08 15:25:52.544  6822  6822 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
01-09 11:43:39.784 32463 32463 E AndroidRuntime: FATAL EXCEPTION: main
01-09 11:43:39.784 32463 32463 E AndroidRuntime: Process: com.hexicallabs.devrant, PID: 32463
01-09 11:43:39.784 32463 32463 E AndroidRuntime: java.lang.IllegalStateException: org.appcelerator.titanium.util.TiBlobLruCache.sizeOf() is reporting inconsistent results!
01-09 11:43:39.784 32463 32463 E AndroidRuntime: 	at android.support.v4.util.LruCache.trimToSize(LruCache.java:167)
01-09 11:43:39.784 32463 32463 E AndroidRuntime: 	at android.support.v4.util.LruCache.evictAll(LruCache.java:271)
01-09 11:43:39.784 32463 32463 E AndroidRuntime: 	at org.appcelerator.titanium.TiApplication.onTrimMemory(TiApplication.java:415)
01-09 11:43:39.784 32463 32463 E AndroidRuntime: 	at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:5585)
01-09 11:43:39.784 32463 32463 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1895)
01-09 11:43:39.784 32463 32463 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
01-09 11:43:39.784 32463 32463 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-09 11:43:39.784 32463 32463 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6809)
01-09 11:43:39.784 32463 32463 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-09 11:43:39.784 32463 32463 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
01-09 11:43:39.784 32463 32463 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```
